do not extract delegate from message before sending?
I'm trying to figure out what the purpose of this code is, because I'm getting:

```
java.lang.AbstractMethodError: com.mockrunner.mock.jms.MockObjectMessage.getBody(Ljava/lang/Class;)Ljava/lang/Object;
	at com.github.thealchemist.fileimport.FilePollerBeanTest$1.onMessage(FilePollerBeanIT.java:40)
	at com.mockrunner.mock.jms.MockMessageConsumer.receiveMessage(MockMessageConsumer.java:86)
	at com.mockrunner.mock.jms.MockQueue.addMessage(MockQueue.java:58)
	at com.mockrunner.mock.jms.MockMessageProducer.send(MockMessageProducer.java:85)
	at com.mockrunner.mock.jms.MockMessageProducer.send(MockMessageProducer.java:53)
	at com.mockrunner.mock.jms.MockQueueSender.send(MockQueueSender.java:25)
	at com.melowe.jms2.compat.Jms2Producer$1.execute(Jms2Producer.java:93)
	at com.melowe.jms2.compat.Jms2Producer$1.execute(Jms2Producer.java:51)
	at com.melowe.jms2.compat.Jms2Util.execute(Jms2Util.java:113)
	at com.melowe.jms2.compat.Jms2Producer.send(Jms2Producer.java:51)
	at com.melowe.jms2.compat.Jms2Producer.send(Jms2Producer.java:126)
```

I'm sending an ```ObjectMessage``` on one send, and on the receiving end, I'm trying to use {{getBody()}} to extract the contents:

```

    @Inject
    private JMSTestModule jmsTestModule;
    
    @Test
    public void testReceivingMessage() throws Exception {
        /*
         * register a listener for the queue so we can make sure the EJB sends a message
         */
        this.jmsTestModule.registerTestMessageListenerForQueue("queue/fileImport", new MessageListener() {
            
            @Override
            public void onMessage(Message message) {
                try {
                    Whatever whatever = message.getBody(Whatever.class);
                    assertNotNull(whatever);
                } catch (JMSException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        /*
         * when
         */
        filePoller.sendMessage(new Whatever());
        
    }
``` 

Any tips on a workaround would be greatly appreciated.